spring.application.name=spring-boot-essentials-jpa

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt.expiration=${JWT_EXPIRATION:900000}
jwt.key=${JWT_KEY:Lck44YGYOtOuIfCRs76dmA69ZYqa96LQm2QKj7tYpYVU1wUJbPWNyz8ekYvz5HY9vDHMDyKVHMZCniFMsunc63iaEqybM2d2YEFJlfYwJVLQNYd8SyZfxrvpTLAm4QNdTkRrYqvIPl3I424aeyB2RsaNL1sKEqQVD1Yfq7EV7LU1ZUQQr0sv1mgThe25igwkKVF5Z7OuOifdnYYVUxyyvdxmk7RT3zI0OUTL0ZLYVfOYRG0PJH3LC7Ngewx8fjfhwJ76MZc4v8MMLIVSouwiBOAiVqQp0Desy2chGKYxnRUl4V4wZi2mmWQe3jrHFnyJYhXbgZ2bJWpdP0Az7RnCpbu7\ }