spring.application.name=spring-boot-essentials-jpa

# Configuração do banco de dados
spring.datasource.url=jdbc:mysql://localhost:3306/gym?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin123

# Configuração JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true